[theme]
primaryColor = "#046663"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F6F6F5"
textColor = "#404035"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50
